import type { Authority } from "./types";

/**
 * Chamber desk authorities. Only reported Supreme Court holdings
 * and named statutes. No invented Andhra Pradesh judgments.
 */
export const AUTHORITIES: Authority[] = [
  {
    id: "arnesh-kumar",
    kind: "case",
    parties: "Arnesh Kumar v. State of Bihar",
    court: "Supreme Court of India",
    citation: "(2014) 8 SCC 273",
    year: "2014",
    bench: "2-Judge",
    area: "bail",
    keywords: [
      "arnesh",
      "498a",
      "498-a",
      "cruelty",
      "arrest",
      "dowry",
      "mechanical",
      "fir",
      "anticipatory",
      "bail",
      "section 41",
      "crpc",
      "bnss",
    ],
    ratio:
      "Arrest is not automatic on a cognizable complaint. For offences punishable with imprisonment up to seven years, the investigating officer must record reasons under Section 41 CrPC (now Section 35 BNSS) that arrest is necessary. Omnibus 498A allegations do not, by themselves, justify mechanical arrest.",
    note: "Use this when the FIR is 498A or another sub-7-year offence and the police have arrested, or threaten to arrest, without recording necessity.",
    kanoonQuery: "Arnesh Kumar v State of Bihar 2014 8 SCC 273",
  },
  {
    id: "satender-antil",
    kind: "case",
    parties: "Satender Kumar Antil v. CBI",
    court: "Supreme Court of India",
    citation: "(2022) 10 SCC 51",
    year: "2022",
    bench: "2-Judge",
    area: "bail",
    keywords: [
      "antil",
      "satender",
      "regular bail",
      "summons",
      "warrant",
      "category",
      "undertrial",
      "bail",
      "arrest",
    ],
    ratio:
      "The Court grouped offences into categories and directed that, where the accused has cooperated and is not likely to abscond, bail should ordinarily follow, especially in summons and warrant cases. Prolonged pre-trial detention is not a substitute for investigation.",
    note: "Useful for regular bail after charge-sheet, and for arguing that the accused who appeared on summons should not be taken into custody as a matter of course.",
    kanoonQuery: "Satender Kumar Antil v CBI 2022 10 SCC 51",
  },
  {
    id: "sibbia",
    kind: "case",
    parties: "Gurbaksh Singh Sibbia v. State of Punjab",
    court: "Supreme Court of India",
    citation: "(1980) 2 SCC 565",
    year: "1980",
    bench: "Constitution Bench",
    area: "bail",
    keywords: [
      "sibbia",
      "anticipatory",
      "438",
      "482 bnss",
      "pre-arrest",
      "bail",
      "apprehension",
    ],
    ratio:
      "Anticipatory bail is not to be confined by a rigid formula. The court balances the liberty of the applicant against the needs of investigation. Conditions may be imposed, but a blanket refusal merely because a serious offence is alleged is not the law.",
    note: "The parent authority for Section 438 CrPC / Section 482 BNSS applications. Pair with Sushila Aggarwal on duration.",
    kanoonQuery: "Gurbaksh Singh Sibbia v State of Punjab 1980 2 SCC 565",
  },
  {
    id: "sushila-aggarwal",
    kind: "case",
    parties: "Sushila Aggarwal v. State (NCT of Delhi)",
    court: "Supreme Court of India",
    citation: "(2020) 5 SCC 1",
    year: "2020",
    bench: "Constitution Bench",
    area: "bail",
    keywords: [
      "sushila",
      "aggarwal",
      "anticipatory",
      "duration",
      "till end of trial",
      "438",
      "482 bnss",
    ],
    ratio:
      "An order of anticipatory bail does not automatically expire when the accused is summoned to court, nor is it limited to a fixed short period unless the court so directs. It can continue till the end of trial, subject to the power to cancel.",
    note: "Cite when the prosecutor argues that anticipatory bail lapses at the first hearing or after a set number of days.",
    kanoonQuery: "Sushila Aggarwal v State NCT of Delhi 2020 5 SCC 1",
  },
  {
    id: "lalita-kumari",
    kind: "case",
    parties: "Lalita Kumari v. Government of Uttar Pradesh",
    court: "Supreme Court of India",
    citation: "(2014) 2 SCC 1",
    year: "2014",
    bench: "Constitution Bench",
    area: "bail",
    keywords: [
      "lalita",
      "kumari",
      "fir",
      "mandatory",
      "cognizable",
      "preliminary inquiry",
      "154 crpc",
      "173 bnss",
    ],
    ratio:
      "Registration of an FIR is mandatory if the information discloses a cognizable offence. A preliminary inquiry is permitted only in the limited categories listed by the Court (family disputes, medical negligence, commercial offences, corruption, and abnormal delay).",
    note: "Use both ways: to compel registration, or to argue that a 498A family dispute was one of the categories where a short preliminary inquiry was open.",
    kanoonQuery: "Lalita Kumari v Government of Uttar Pradesh 2014 2 SCC 1",
  },
  {
    id: "bhajan-lal",
    kind: "case",
    parties: "State of Haryana v. Bhajan Lal",
    court: "Supreme Court of India",
    citation: "1992 Supp (1) SCC 335",
    year: "1992",
    bench: "2-Judge",
    area: "bail",
    keywords: [
      "bhajan",
      "quash",
      "482",
      "528 bnss",
      "fir",
      "inherent",
      "categories",
    ],
    ratio:
      "The inherent power to quash may be used in the illustrative categories set out in the judgment, including where the allegations even if accepted in full do not disclose an offence, or where the proceeding is manifestly attended with mala fides.",
    note: "The working checklist for a quashing petition. Do not treat the categories as exhaustive.",
    kanoonQuery: "State of Haryana v Bhajan Lal 1992 Supp 1 SCC 335",
  },
  {
    id: "joginder-kumar",
    kind: "case",
    parties: "Joginder Kumar v. State of Uttar Pradesh",
    court: "Supreme Court of India",
    citation: "(1994) 4 SCC 260",
    year: "1994",
    bench: "3-Judge",
    area: "bail",
    keywords: ["joginder", "arrest", "rights", "counsel", "friends", "detention"],
    ratio:
      "An arrest cannot be made merely because it is lawful to do so. The officer must be able to justify the arrest, and the arrested person has the right to have a friend or counsel informed.",
    note: "Still cited with Arnesh Kumar on the necessity of arrest.",
    kanoonQuery: "Joginder Kumar v State of Uttar Pradesh 1994 4 SCC 260",
  },
  {
    id: "vineeta-sharma",
    kind: "case",
    parties: "Vineeta Sharma v. Rakesh Sharma",
    court: "Supreme Court of India",
    citation: "(2020) 9 SCC 1",
    year: "2020",
    bench: "3-Judge",
    area: "family",
    keywords: [
      "vineeta",
      "daughter",
      "coparcener",
      "hindu succession",
      "2005",
      "partition",
      "hsa",
      "father alive",
    ],
    ratio:
      "A daughter is a coparcener by birth, in the same manner as a son, with effect from 9 September 2005. The living status of the father on that date does not control the right. A preliminary decree that has not been given final effect does not freeze the share.",
    note: "Lead authority for a daughter's share in a Hindu joint family partition after the 2005 amendment.",
    kanoonQuery: "Vineeta Sharma v Rakesh Sharma 2020 9 SCC 1",
  },
  {
    id: "danamma",
    kind: "case",
    parties: "Danamma @ Suman Surpur v. Amar",
    court: "Supreme Court of India",
    citation: "(2018) 3 SCC 343",
    year: "2018",
    bench: "2-Judge",
    area: "family",
    keywords: ["danamma", "daughter", "partition", "coparcener", "hindu succession"],
    ratio:
      "Daughters have a share in the coparcenary equal to sons. The Court applied the 2005 amendment to a partition that was still open.",
    note: "Read with Vineeta Sharma, which settled the conflict with Prakash v. Phulavati.",
    kanoonQuery: "Danamma v Amar 2018 3 SCC 343",
  },
  {
    id: "rajnesh-neha",
    kind: "case",
    parties: "Rajnesh v. Neha",
    court: "Supreme Court of India",
    citation: "(2021) 2 SCC 324",
    year: "2021",
    bench: "2-Judge",
    area: "family",
    keywords: [
      "rajnesh",
      "neha",
      "maintenance",
      "125 crpc",
      "144 bnss",
      "affidavit",
      "income",
    ],
    ratio:
      "Every maintenance proceeding must be accompanied by a comprehensive affidavit of assets and liabilities in the form annexed to the judgment. Overlapping claims under different statutes are to be disclosed and adjusted.",
    note: "File the affidavit with any 125 CrPC / 144 BNSS or HMA maintenance application. Courts now expect it.",
    kanoonQuery: "Rajnesh v Neha 2021 2 SCC 324",
  },
  {
    id: "suraj-lamp",
    kind: "case",
    parties: "Suraj Lamp and Industries Pvt. Ltd. v. State of Haryana",
    court: "Supreme Court of India",
    citation: "(2012) 1 SCC 656",
    year: "2012",
    bench: "3-Judge",
    area: "revenue",
    keywords: [
      "suraj lamp",
      "gpa",
      "power of attorney",
      "sale",
      "registration",
      "mutation",
      "agreement to sell",
      "will",
      "immovable",
    ],
    ratio:
      "An immovable property cannot be transferred by a general power of attorney, an agreement to sell, or a will presented as a substitute for a registered conveyance. Title passes only by a registered deed. GPA transactions do not confer ownership.",
    note: "Cite when a client holds only a GPA or an unregistered agreement and wants mutation or a declaration of title.",
    kanoonQuery: "Suraj Lamp v State of Haryana 2012 1 SCC 656",
  },
  {
    id: "anjanappa",
    kind: "case",
    parties: "T. Anjanappa v. Somalingappa",
    court: "Supreme Court of India",
    citation: "(2006) 7 SCC 570",
    year: "2006",
    bench: "2-Judge",
    area: "revenue",
    keywords: [
      "anjanappa",
      "adverse possession",
      "hostile",
      "title",
      "limitation",
      "possession",
      "land",
    ],
    ratio:
      "Adverse possession requires possession that is nec vi, nec clam, nec precario: adequate in continuity, publicity, and extent, and hostile to the true owner. Mere long possession is not enough.",
    note: "Use both to prove and to defeat an adverse-possession claim over agricultural land.",
    kanoonQuery: "T Anjanappa v Somalingappa 2006 7 SCC 570",
  },
  {
    id: "karnataka-wakf",
    kind: "case",
    parties: "Karnataka Board of Wakf v. Government of India",
    court: "Supreme Court of India",
    citation: "(2004) 10 SCC 779",
    year: "2004",
    bench: "2-Judge",
    area: "revenue",
    keywords: ["wakf", "adverse possession", "title", "revenue", "possession"],
    ratio:
      "A person who sets up adverse possession must clearly plead and prove when possession became adverse. Inconsistency between a title claim and an adverse-possession claim is usually fatal.",
    note: "Often paired with Anjanappa in land suits.",
    kanoonQuery: "Karnataka Board of Wakf v Government of India 2004 10 SCC 779",
  },
  {
    id: "ghanshyam-dass",
    kind: "case",
    parties: "Ghanshyam Dass v. Dominion of India",
    court: "Supreme Court of India",
    citation: "(1984) 3 SCC 46",
    year: "1984",
    bench: "2-Judge",
    area: "civil",
    keywords: [
      "ghanshyam",
      "section 80",
      "80 cpc",
      "notice",
      "government",
      "suit",
      "promissory",
    ],
    ratio:
      "Section 80 CPC is mandatory for a suit against the Government or a public officer in an official capacity. The notice must state the cause of action, the name and description of the plaintiff, and the relief. Substantial compliance, not ritual, is the test.",
    note: "File the notice before any money or land suit against the State, a municipality, or a public officer. Wait two months unless urgent interlocutory relief is sought.",
    kanoonQuery: "Ghanshyam Dass v Dominion of India 1984 3 SCC 46",
  },
  {
    id: "bihari-chowdhary",
    kind: "case",
    parties: "Bihari Chowdhary v. State of Bihar",
    court: "Supreme Court of India",
    citation: "(1984) 2 SCC 627",
    year: "1984",
    bench: "2-Judge",
    area: "civil",
    keywords: ["bihari", "chowdhary", "section 80", "80 cpc", "notice", "government"],
    ratio:
      "A suit instituted without the statutory notice is not maintainable. The object of the notice is to give the Government a chance to consider the claim and avoid litigation.",
    note: "If notice was skipped, withdraw and refile after notice rather than invite a rejection.",
    kanoonQuery: "Bihari Chowdhary v State of Bihar 1984 2 SCC 627",
  },
  {
    id: "dalpat-kumar",
    kind: "case",
    parties: "Dalpat Kumar v. Prahlad Singh",
    court: "Supreme Court of India",
    citation: "(1992) 1 SCC 719",
    year: "1992",
    bench: "2-Judge",
    area: "civil",
    keywords: [
      "dalpat",
      "injunction",
      "temporary",
      "prima facie",
      "balance of convenience",
      "irreparable",
      "order 39",
    ],
    ratio:
      "A temporary injunction requires a prima facie case, balance of convenience, and a showing that refusal would cause irreparable injury. The court does not decide the suit at this stage.",
    note: "The three-part test for every Order XXXIX application.",
    kanoonQuery: "Dalpat Kumar v Prahlad Singh 1992 1 SCC 719",
  },
  {
    id: "salem-bar",
    kind: "case",
    parties: "Salem Advocate Bar Association v. Union of India",
    court: "Supreme Court of India",
    citation: "(2005) 6 SCC 344",
    year: "2005",
    bench: "3-Judge",
    area: "civil",
    keywords: [
      "salem",
      "amendment",
      "case management",
      "written statement",
      "90 days",
      "cpc",
    ],
    ratio:
      "The 1999 and 2002 CPC amendments are valid. The 90-day period for a written statement is the ordinary rule; the court may extend it in writing for reasons, but delay is no longer casual.",
    note: "Cite when seeking, or opposing, condonation of delay in filing a written statement.",
    kanoonQuery: "Salem Advocate Bar Association v Union of India 2005 6 SCC 344",
  },
  {
    id: "ima-shantha",
    kind: "case",
    parties: "Indian Medical Association v. V.P. Shantha",
    court: "Supreme Court of India",
    citation: "(1995) 6 SCC 651",
    year: "1995",
    bench: "3-Judge",
    area: "consumer",
    keywords: [
      "shantha",
      "medical",
      "negligence",
      "service",
      "consumer",
      "hospital",
      "deficiency",
    ],
    ratio:
      "Medical services rendered for a fee are 'services' under the consumer law. Free services at a government hospital fall outside, but a paying patient in the same hospital is a consumer.",
    note: "Still the starting point for a medical-negligence consumer complaint.",
    kanoonQuery: "Indian Medical Association v VP Shantha 1995 6 SCC 651",
  },
  {
    id: "lda-gupta",
    kind: "case",
    parties: "Lucknow Development Authority v. M.K. Gupta",
    court: "Supreme Court of India",
    citation: "(1994) 1 SCC 243",
    year: "1994",
    bench: "2-Judge",
    area: "consumer",
    keywords: [
      "lucknow",
      "development",
      "housing",
      "deficiency",
      "statutory",
      "consumer",
      "allotment",
    ],
    ratio:
      "A statutory housing authority that undertakes to construct or allot is providing a service. Delay, defective construction, and unfair allotment are deficiency in service, and compensation can include for harassment.",
    note: "Use against housing boards, development authorities, and builders on delay and defect.",
    kanoonQuery: "Lucknow Development Authority v MK Gupta 1994 1 SCC 243",
  },
  {
    id: "pioneer-govindan",
    kind: "case",
    parties: "Pioneer Urban Land and Infrastructure Ltd. v. Govindan Raghavan",
    court: "Supreme Court of India",
    citation: "(2019) 5 SCC 725",
    year: "2019",
    bench: "2-Judge",
    area: "consumer",
    keywords: [
      "pioneer",
      "builder",
      "delay",
      "one-sided",
      "agreement",
      "refund",
      "consumer",
    ],
    ratio:
      "A one-sided builder-buyer agreement that penalises the buyer heavily for delay while letting the builder delay with a token interest is unfair. The buyer may seek refund and compensation.",
    note: "Standard authority for delayed apartment possession complaints.",
    kanoonQuery: "Pioneer Urban Land v Govindan Raghavan 2019 5 SCC 725",
  },
  {
    id: "karunakar",
    kind: "case",
    parties: "Managing Director, ECIL v. B. Karunakar",
    court: "Supreme Court of India",
    citation: "(1993) 4 SCC 727",
    year: "1993",
    bench: "Constitution Bench",
    area: "service",
    keywords: [
      "karunakar",
      "enquiry",
      "report",
      "disciplinary",
      "natural justice",
      "service",
    ],
    ratio:
      "A copy of the enquiry report must be furnished to the delinquent employee before the disciplinary authority takes a decision. Failure is a breach of natural justice, subject to a prejudice test.",
    note: "First document to demand in any departmental enquiry file.",
    kanoonQuery: "ECIL v B Karunakar 1993 4 SCC 727",
  },
  {
    id: "tulsiram-patel",
    kind: "case",
    parties: "Union of India v. Tulsiram Patel",
    court: "Supreme Court of India",
    citation: "(1985) 3 SCC 398",
    year: "1985",
    bench: "Constitution Bench",
    area: "service",
    keywords: [
      "tulsiram",
      "article 311",
      "dismissal",
      "enquiry",
      "second proviso",
      "service",
    ],
    ratio:
      "Article 311(2) ordinarily requires an enquiry. The second proviso permits dismissal without enquiry in the three listed situations, but the authority must record reasons and the action remains open to judicial review on mala fides and statutory compliance.",
    note: "Use when a government servant is dismissed without a regular enquiry.",
    kanoonQuery: "Union of India v Tulsiram Patel 1985 3 SCC 398",
  },
  {
    id: "statute-80-cpc",
    kind: "statute",
    parties: "Code of Civil Procedure, 1908, Section 80",
    court: "Statute",
    citation: "s. 80 CPC",
    year: "1908",
    area: "civil",
    keywords: [
      "section 80",
      "80 cpc",
      "notice",
      "government",
      "public officer",
      "two months",
      "promissory",
    ],
    ratio:
      "No suit shall be instituted against the Government or against a public officer in respect of any act purporting to be done in official duty until two months after a written notice stating the cause of action, name, description, and relief. Urgent relief may be sought with leave of the court.",
    note: "Always check whether the defendant is the State, a local body, or a public officer before filing.",
    kanoonQuery: "Section 80 Code of Civil Procedure 1908",
  },
  {
    id: "statute-438",
    kind: "statute",
    parties: "Section 438 CrPC / Section 482 BNSS",
    court: "Statute",
    citation: "s. 438 CrPC · s. 482 BNSS",
    year: "1973",
    area: "bail",
    keywords: [
      "438",
      "482 bnss",
      "anticipatory",
      "pre-arrest",
      "sessions",
      "high court",
    ],
    ratio:
      "The High Court or the Court of Session may direct that in the event of arrest the applicant be released on bail. The Bharatiya Nagarik Suraksha Sanhita, 2023 relocates the provision to Section 482. Sibbia and Sushila Aggarwal still govern the discretion.",
    note: "File at the Sessions Court that has territorial reach over the police station, or at the High Court.",
    kanoonQuery: "Section 438 CrPC anticipatory bail",
  },
  {
    id: "statute-hsa-6",
    kind: "statute",
    parties: "Hindu Succession Act, 1956, Section 6",
    court: "Statute",
    citation: "s. 6 HSA (2005 amendment)",
    year: "2005",
    area: "family",
    keywords: [
      "hindu succession",
      "section 6",
      "coparcener",
      "daughter",
      "partition",
      "2005",
    ],
    ratio:
      "On and from 9 September 2005, a daughter of a coparcener becomes a coparcener by birth in her own right, with the same rights and liabilities as a son, including the right to seek partition.",
    note: "Vineeta Sharma is the controlling reading of this section.",
    kanoonQuery: "Hindu Succession Act section 6 daughter coparcener",
  },
  {
    id: "statute-ap-ppb",
    kind: "statute",
    parties: "A.P. Rights in Land and Pattadar Pass Books Act, 1971",
    court: "Statute",
    citation: "AP PPB Act, 1971",
    year: "1971",
    area: "revenue",
    keywords: [
      "adangal",
      "pahani",
      "pattadar",
      "passbook",
      "mutation",
      "1b",
      "revenue",
      "andhra",
      "tahsildar",
      "rdo",
      "encumbrance",
      "ec",
      "noc",
    ],
    ratio:
      "The Record of Rights (adangal / 1-B) and the pattadar passbook are the working evidence of cultivation and of the person recorded as enjoyer. Mutation after death or transfer is an executive act of the Tahsildar. It does not, by itself, confer title. Title still depends on succession, a registered deed, or a decree.",
    note: "In Anantapur chamber work: match the adangal, the 1-B, the EC, and the registered deed. If they do not tell the same story, say so in the application.",
    kanoonQuery: "Andhra Pradesh Rights in Land and Pattadar Pass Books Act 1971",
  },
  {
    id: "statute-cpa",
    kind: "statute",
    parties: "Consumer Protection Act, 2019, Section 35",
    court: "Statute",
    citation: "s. 35 CPA 2019",
    year: "2019",
    area: "consumer",
    keywords: [
      "consumer",
      "complaint",
      "section 35",
      "deficiency",
      "district commission",
      "forum",
    ],
    ratio:
      "A consumer complaint is filed before the District, State, or National Commission according to value. It must set out the consumer relationship, the deficiency or unfair practice, the chronology, and the relief under the 2019 Act.",
    note: "Check pecuniary limits before choosing the forum. Attach the invoice, the builder agreement, or the policy.",
    kanoonQuery: "Consumer Protection Act 2019 section 35 complaint",
  },
];

export const PRACTICE_AREAS = [
  {
    id: "revenue" as const,
    title: "Revenue and land",
    body: "Adangal, 1-B, EC, NOC, mutation, and the AP pattadar passbook. Most Anantapur files start here.",
    acts: "AP PPB Act 1971 · Registration Act · Transfer of Property Act",
    query: "mutation of name in adangal after father's death without registered will",
    draft: "mutation",
  },
  {
    id: "bail" as const,
    title: "Bail and criminal",
    body: "Anticipatory bail, regular bail, quashing, 498A, and the new BNSS numbers for the same work.",
    acts: "BNSS 2023 · CrPC 1973 · BNS 2023 · NDPS Act",
    query: "anticipatory bail in 498A where the FIR is omnibus and arrest is threatened",
    draft: "bail",
  },
  {
    id: "family" as const,
    title: "Family and partition",
    body: "Daughter's coparcenary share, partition among brothers, succession, and maintenance affidavits.",
    acts: "Hindu Succession Act · Hindu Marriage Act · s. 125 CrPC / 144 BNSS",
    query: "partition suit by daughter after 2005 amendment father died later",
    draft: "partition",
  },
  {
    id: "civil" as const,
    title: "Civil and contract",
    body: "Money recovery, Section 80 notices, injunctions, and written statements that meet the 90-day rule.",
    acts: "CPC 1908 · Contract Act · Specific Relief Act",
    query: "is section 80 CPC notice required before a suit on a promissory note against a municipality",
    draft: "notice",
  },
  {
    id: "consumer" as const,
    title: "Consumer forums",
    body: "Builder delay, housing boards, insurance, and medical service complaints under the 2019 Act.",
    acts: "Consumer Protection Act 2019",
    query: "consumer complaint against builder for delayed possession refund",
    draft: "consumer",
  },
  {
    id: "service" as const,
    title: "Service matters",
    body: "Departmental enquiry, the enquiry report, Article 311, and AP / TS service rules.",
    acts: "Article 311 · AP State and Subordinate Service Rules",
    query: "dismissal of government servant without supplying enquiry report",
    draft: "ws",
  },
];
