import './styles/global.css';
import { mountNavbar } from './components/navbar.js';
import { mountHero } from './components/hero.js';
import { mountFeatures } from './components/features.js';
import { mountJudgments } from './components/judgments.js';
import { mountNews } from './components/news.js';
import { mountFooter } from './components/footer.js';
import { mountDraftingPanel } from './components/draftingPanel.js';
import { generateLegalUpdate } from './services/aiService.js';
import { getTheme, setTheme, toggleTheme } from './services/storage.js';
import { injectSpeedInsights } from '@vercel/speed-insights';

/* ─── Drafting page ─── */
function renderDrafting() {
  return `
  <section class="section" id="drafting-hero" style="text-align:center;padding-top:120px">
    <h1 style="font-family:var(--font-heading);font-size:clamp(2rem,5vw,3rem);color:var(--color-primary);margin-bottom:16px">AI Drafting <span class="gradient-text">Assistant</span></h1>
    <p style="color:var(--color-text-muted);max-width:640px;margin:0 auto;font-size:1.1rem">Generate court-ready petitions for Supreme Court, High Court & District Courts. Free for all advocates.</p>
  </section>
  <div class="container" id="ai-panel-mount" style="padding-bottom:var(--space-3xl)"></div>
  <section style="background:var(--color-primary);color:rgba(255,255,255,0.8);padding:var(--space-xl);text-align:center;font-size:0.9rem">
    <p><strong style="color:var(--color-accent)">⚠️ Important:</strong> All drafts must be reviewed by a qualified advocate before filing. NyayaVedika is a drafting tool, not legal advice.</p>
  </section>`;
}

/* ─── Legal Updates page ─── */
function renderLegalUpdates() {
  const topics = [
    'Section 37 NDPS Act — Twin Conditions for Bail',
    'Article 226 vs 227 — High Court Powers',
    'Default Bail under Section 187 BNSS',
    'Quashing under Section 528 BNSS / 482 CrPC',
    'Anticipatory Bail under BNS/BNSS',
  ];
  return `
  <section class="section" style="text-align:center;padding-top:120px">
    <h1 style="font-family:var(--font-heading);font-size:clamp(2rem,5vw,3rem);color:var(--color-primary);margin-bottom:16px">📰 Legal Updates & Digest</h1>
    <p style="color:var(--color-text-muted);max-width:640px;margin:0 auto">Enter any legal topic — get a comprehensive AI-generated digest with statutes, landmark judgments, and practice tips.</p>
  </section>
  <section style="padding:var(--space-2xl) 0 var(--space-4xl)">
    <div class="container">
      <div style="display:flex;gap:12px;margin-bottom:24px;flex-wrap:wrap">
        <input class="form-input form-input-lg" id="legal-topic-input" placeholder="e.g. Section 37 NDPS Act twin conditions for bail..." style="flex:1;min-width:250px;padding:14px 20px;border:1px solid var(--color-border);border-radius:var(--radius-full);font-size:1rem" />
        <button class="btn btn-primary" id="btn-generate-update">Generate Digest</button>
      </div>
      <div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:32px">
        ${topics.map(t => `<button class="topic-chip" data-topic="${t}" style="padding:8px 16px;border:1px solid var(--color-border);border-radius:var(--radius-full);background:var(--color-surface);color:var(--color-text-muted);font-size:0.85rem;cursor:pointer;transition:all var(--duration-fast)">${t}</button>`).join('')}
      </div>
      <div id="update-loading" style="display:none;text-align:center;padding:40px"><p>Generating digest...</p></div>
      <div id="update-result" style="display:none"><div id="update-result-body" style="background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg);padding:var(--space-xl);white-space:pre-wrap;line-height:1.8;font-size:0.95rem"></div>
      <div style="margin-top:16px;display:flex;gap:8px"><button class="btn btn-secondary btn-sm" id="btn-update-copy">Copy</button><button class="btn btn-secondary btn-sm" id="btn-update-download">Download .txt</button></div></div>
      <div id="update-error" style="display:none;color:var(--color-error);padding:var(--space-md);text-align:center"></div>
    </div>
  </section>
  <section style="background:var(--color-primary);color:rgba(255,255,255,0.8);padding:var(--space-xl);text-align:center;font-size:0.9rem">
    <p><strong style="color:var(--color-accent)">⚠️ AI-Generated:</strong> Legal updates are generated by AI. Always verify with primary sources before relying on this information.</p>
  </section>`;
}

function attachLegalUpdatesEvents() {
  const input = document.getElementById('legal-topic-input');
  const btn = document.getElementById('btn-generate-update');
  const loading = document.getElementById('update-loading');
  const result = document.getElementById('update-result');
  const resultBody = document.getElementById('update-result-body');
  const error = document.getElementById('update-error');

  async function run(topic) {
    if (!topic) { error.style.display='block'; error.textContent='Please enter a legal topic.'; return; }
    error.style.display='none'; result.style.display='none'; loading.style.display='block';
    try {
      const out = await generateLegalUpdate(topic);
      loading.style.display='none'; resultBody.textContent = out; result.style.display='block';
    } catch (err) {
      loading.style.display='none'; error.style.display='block'; error.textContent = err.message;
    }
  }

  btn?.addEventListener('click', () => run(input?.value));
  document.querySelectorAll('.topic-chip').forEach(c => c.addEventListener('click', () => { input.value = c.dataset.topic; run(c.dataset.topic); }));
  document.getElementById('btn-update-copy')?.addEventListener('click', () => { navigator.clipboard.writeText(resultBody?.innerText); });
  document.getElementById('btn-update-download')?.addEventListener('click', () => {
    const blob = new Blob([resultBody?.innerText], {type:'text/plain'});
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download=`nyayavedika-digest-${Date.now()}.txt`; a.click();
  });
}

/* ─── Home page ─── */
function renderHome() {
  const app = document.getElementById('app');
  const navbar = document.createElement('div'); app.appendChild(navbar); mountNavbar(navbar);
  const hero = document.createElement('div'); app.appendChild(hero); mountHero(hero);
  const features = document.createElement('div'); app.appendChild(features); mountFeatures(features);
  const judgments = document.createElement('div'); app.appendChild(judgments); mountJudgments(judgments);
  const news = document.createElement('div'); app.appendChild(news); mountNews(news);
  const cta = document.createElement('section');
  cta.innerHTML = `<div class="container" style="text-align:center;padding:var(--space-4xl) 0">
    <h2 style="font-family:var(--font-heading);font-size:clamp(1.8rem,3vw,2.5rem);margin-bottom:16px">Start drafting like a <span class="gradient-text">top-tier chamber</span> — for free</h2>
    <p style="color:var(--color-text-muted);max-width:600px;margin:0 auto 32px;font-size:1.1rem">No subscriptions. No paywalls. Just powerful AI drafting for every Indian advocate.</p>
    <a href="#drafting" class="btn btn-primary" style="font-size:1.1rem;padding:16px 36px">Open AI Drafting Tool — Free</a>
  </div>`;
  app.appendChild(cta);
  const footer = document.createElement('div'); app.appendChild(footer); mountFooter(footer);
  setupScrollReveal();
}

/* ─── Scroll Reveal ─── */
function setupScrollReveal() {
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
    document.querySelectorAll('[data-reveal]').forEach(el => { el.classList.add('revealed'); });
    return;
  }
  const observer = new IntersectionObserver(entries => {
    entries.forEach(e => { if (e.isIntersecting) e.target.classList.add('revealed'); });
  }, { threshold: 0.1 });
  document.querySelectorAll('[data-reveal]').forEach(el => observer.observe(el));
}

/* ─── Routing ─── */
const routes = { 'drafting': renderDrafting, 'legal-updates': renderLegalUpdates };
const hasRoutes = { 'drafting': true, 'legal-updates': true };

function getPage() {
  const h = window.location.hash.replace('#', '');
  return routes[h] ? h : '';
}

function render() {
  const app = document.getElementById('app');
  app.innerHTML = '';
  const page = getPage();

  if (page) {
    const navbar = document.createElement('div'); app.appendChild(navbar); mountNavbar(navbar);
    const content = document.createElement('div'); content.innerHTML = routes[page](); app.appendChild(content);
    const footer = document.createElement('div'); app.appendChild(footer); mountFooter(footer);

    if (page === 'drafting') mountDraftingPanel('ai-panel-mount');
    if (page === 'legal-updates') setTimeout(attachLegalUpdatesEvents, 50);
  } else {
    renderHome();
  }
  window.scrollTo(0, 0);
}

/* ─── Init ─── */
window.addEventListener('hashchange', render);
setTheme(getTheme());
injectSpeedInsights();
render();
